dist: xenial
language: c++
compiler: clang
addons:
  apt:
    packages:
      - libboost-test-dev
      - libspdlog-dev
script:
  - cat $TRAVIS_BUILD_NUMBER
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package

before_deploy:
  - sed -i "s/__VERSION__/$TRAVIS_BUILD_NUMBER/g" bintray-descriptor.json
  - cat bintray-descriptor.json

deploy:
  skip_cleanup: true
  provider: bintray
  file: bintray-descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
