dist: xenial
language: c++
compiler: clang
addons:
  apt:
    packages:
      - libboost-test-dev
      - libspdlog-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
